### PR TITLE
Fix ordered set with map

### LINKED ISSUE #115: OrderedSet is changing item ordering (@4.0.0-rc.11+)
*From @pixmaster on Wed, 12 Dec 2018 15:37:49 GMT*

```javascript
const { OrderedSet, Map } = require('immutable@4.0.0-rc.11')
const i=[2];
OrderedSet([ Map({b:1, a:true}), Map({b:2,a:true}), Map({b:3,a:true}) ])
  .map((t) => {
  if (i.includes(t.get('b'))) return t.set('a', false);
  return t;
  })
  .toJS()
```
Result
image

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1663*

### PR DESCRIPTION
**Pull request by jdeniau**
Fixes #115 

This issue has been introduced by https://github.com/immutable-js/immutable-js/pull/1606 : to keep the reference equality, it did remove and add all values that changes.

I tried several implementations to fix this, and finally used the other approach that @jessezhang91 dropped for a really small performance reason : replace the `.map` by a `.mapEntries` and keep track if at least one value did change.

### CODE REVIEW

File: src/Set.js [hunk 1]
```diff
@@ -82,19 +82,23 @@ export class Set extends SetCollection {
...
-      }
-    });
-    return this.withMutations((set) => {
-      removes.forEach((value) => set.remove(value));
-      adds.forEach((value) => set.add(value));
-    });
+    // keep track if the set is altered by the map function
+    let didChanges = false;
+
+    const newMap = updateSet(
```
Comment (jdeniau) [inline src/Set.js:88]: I reused `updateSet` here as it was the base implementation (see [here](https://github.com/immutable-js/immutable-js/pull/1606/files#diff-f6aa3e181d81c115fe15d0c5d744a41f4d9c1f95f811e05137894ea215f3370d) for the original implementation)

**Review by Methuselah96 — APPROVED** [review]
Thanks! I would be interested in seeing if we could get this working using `withMutations` (would probably have to change `Map#mapEntries`, but this looks like it will work as well.
