### PR TITLE
Record clear does work

### LINKED ISSUE #85: `clear()` doesn't return to default values
*From @lovincyrus on Wed, 01 Aug 2018 07:36:11 GMT*

### What happened

Issue with `clear()` — https://facebook.github.io/immutable-js/docs/#/Record/clear

When `clear()`, it doesn't return to its default values.

### How to reproduce

```
const User = Record({
  roles: List()
})

const assertEqual = (a, b) => {
  if (a.equals(b)) return true
  throw new Error('Failed equality check')
}

const user_0 = new User({ roles: ['superuser', 'admin'] })
const user_1 = user_0.clear();

assertEqual(user_1.roles, List())

const user_3 = user_0.withMutations(mutable => mutable.reset())

assertEqual(user_3.roles, List())
```

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1565*

### PR DESCRIPTION
**Pull request by jdeniau**
Fixes #85

### CODE REVIEW

File: __tests__/Record.ts [hunk 1]
```diff
@@ -253,4 +253,25 @@ describe('Record', () => {
...
+    });
+
+    const user_0 = new User({
+      name: 'John',
+      roles: ['superuser', 'admin'],
+    });
+    const user_1 = user_0.clear();
+
+    expect(user_1.name).toBe('default name');
+    expect(user_1.roles).toEqual(List());
```
Comment (Methuselah96) [inline __tests__/Record.ts:275]: The problem occurred when you add:
```
const user_3 = user_0.withMutations(mutable => mutable.clear());
expect(user_3.roles).toEqual(List());
```

Can you try adding that and see if it still works?

**Review by Methuselah96 — CHANGES_REQUESTED** [review]

File: __tests__/Record.ts (hunk 1 above)
Comment (jdeniau) [reply __tests__/Record.ts:275]: In the default issue, `roles` is an array, not an immutable List object but yes I will add this test case to be sure that it works as expected

Comment (jdeniau) [reply __tests__/Record.ts:275]: You are right : calling clear on is mutable does not works anymore. I will investigate on this

File: src/Record.js [hunk 2]
```diff
@@ -151,8 +151,14 @@ export class Record {
   }
 
   clear() {
+    if (this.__ownerID) {
+      this._values.clear();
+
+      return this;
+    }
```
Comment (jdeniau) [inline src/Record.js:158]: I inspired myself with the [the 3.8.2 implementation](https://github.com/immutable-js-oss/immutable-js/blob/v3.8.2/src/Record.js#L67-L70)

The issue here was that clearing the list of values and then calling `setSize` does set the elements to be "null" instead of "undefined.
Breaking early without calling setSize does fix the problem apparently.

**Comment by jdeniau** [comment]
@Methuselah96 this is fixed

File: src/Record.js (hunk 2 above)
Comment (Methuselah96) [reply src/Record.js:158]: I'm wary of this change because before this change `this._values` will be always be the correct size.

My suggested alternative change would be to make it so that `List` returns `undefined` when an element isn't set (which seems to be the intention based on [the `List#setSize()` documentation](https://immutable-js.github.io/immutable-js/docs/#/List/setSize) and based on the fact that it works like that in the majority of cases). In order to accomplish this we would change [the `List#clear()` logic](https://github.com/immutable-js-oss/immutable-js/blob/master/src/List.js#L109-L110) from:
```
this._root = this._tail = null;
this.__hash = undefined;
```
to:
```
this._root = this._tail = this.__hash = undefined;
```

I'm fairly certain this won't break anything because `_root` and `_tail` start as `undefined` [when an `emptyList()` is created](https://github.com/immutable-js-oss/immutable-js/blob/master/src/List.js#L414-L417).

**Review by Methuselah96 — CHANGES_REQUESTED** [review]

File: src/Record.js (hunk 2 above)
Comment (jdeniau) [reply src/Record.js:158]: @Methuselah96 you were right. This is a better approach. I added tests for both `Record` and `List.clear.setSize`

**Review by Methuselah96 — APPROVED** [review]

**Comment by Methuselah96** [comment]
@jdeniau Looks like a lint failure:
```
__tests__/List.ts:798:33

ERROR: 798:33  no-shadowed-variable  Shadowed name: 'l'
```

**Comment by jdeniau** [comment]
@Methuselah96 Sorry about that, this is fixed

**Comment by Methuselah96** [comment]
@jdeniau Merge conflict.

**Comment by Methuselah96** [comment]
Thanks!
